(function() { var aa=window,ba=Function,ca=LanguageDisplays,da=document,ga=Math,ha=Array,f=localStorage,h=Error,ia=parseInt,ja=String;function ka(a,b){return a.display=b}function la(a,b){return a.innerHTML=b}function l(a,b){return a.type=b}function m(a,b){return a.className=b}
var ma="appendChild",na="getChildren",n="getParent",p="replace",oa="charAt",pa="insertBefore",qa="charCode",ra="createElement",sa="keyCode",ta="firstChild",ua="setAttribute",va="handleEvent",r="getTree",wa="childNodes",xa="bind",s="code",t="toString",ya="propertyIsEnumerable",u="split",v="style",za="contains",Aa="apply",x="push",Ba="test",Ca="slice",Da="nodeType",Ea="localNames",Fa="removed",y="indexOf",z="type",A="length",Ga="language",B="prototype",Ha="document",Ia="body",Ja="removeChild",C="call",
Ka="lastIndexOf",La="getAttribute",Ma="navigator",Na="parentNode",Oa="splice",Pa="join",Qa="toLowerCase",D="",E=" ",Ra=" - ",Sa=' name="',Ta=' type="',Ua='"',Va='" id="',Wa='" style="',Xa='" style="padding-',Ya='">',Za='"></span>',$a="#",ab="&",bb="&amp;",cb="&gt;",db="&lt;",eb="&quot;",fb="(\\d*)(\\D*)",gb="*",hb=",",ib="-",jb="-100",kb="-handwrit",lb="-i0",mb="-k0",nb="-t-",ob="-t-i0-und",pb="-t-k0-und",qb="-t-und-latn-k0-und",rb="-und",sb=".",tb=".ita-icon-",ub=".label",vb="0",wb="525",xb=":",
yb=";",zb="<",Ab="</div>",Bb="</div></div>",Cb="</span>",Db="<br>",Eb='<div class="',Fb='<span class="',Gb='<span style="display:inline-block" class="',Hb='<span type="expand" style="display:inline-block" class="',Ib="<span>",Jb=">",Kb="BackgroundImageCache",Lb="Component already rendered",Mb="LI",Nb="Nederlands",Ob="SPAN",Pb="Unable to set parent component",Qb="[object Array]",Rb="[object Function]",Sb="[object Window]",Tb="_",Ub="activedescendant",Vb="additions text",Wb="af-t-i0-handwrit",Xb="amp",
Yb="aria-",Zb="array",$b="background-position:",ac="be-t-i0-handwrit",bc="beforecollapse",cc="beforeexpand",dc="bg-t-i0-handwrit",ec="bg-t-k0-qwerty",fc="block",gc="blur",hc="bn-t-und-latn-k0-und",ic="body",jc="br",kc="ca-t-i0-handwrit",lc="call",mc="change",nc="chext-arrowbutton-",oc="chr-t-und-latn-k0-und",pc="class",qc="click",rc="collapse",sc="cs-t-i0-handwrit",tc="cs-t-k0-qwertz",uc="current_layout",vc="cy-t-i0-handwrit",wc="da-t-i0-handwrit",xc="data-",yc="dblclick",zc="de-ch-t-k0-und",Ac="de-t-i0-handwrit",
Bc="direction",Cc="disable",Dc="display:none;",Ec="div",Fc="document",Gc="down",F="en",Hc="en-t-i0-handwrit",Ic="en-t-k0-dvorak",Jc="en-us-t-k0-intl",Kc="en_us",Lc="enable",Mc="es-t-i0-handwrit",Nc="es-t-k0-und",Oc="et-t-i0-handwrit",Pc="eu-t-i0-handwrit",Qc="event",Rc="expand",Sc="expanded",Tc="false",Uc="fi-t-i0-handwrit",Vc="fil-t-i0-handwrit",Wc="focus",Xc="focused",Yc="focusin",Zc="focusout",$c="for",ad="fr-t-i0-handwrit",G="function",bd="g",cd="ga-t-i0-handwrit",dd="gl-t-i0-handwrit",ed="goog-tree-collapsed-folder-icon",
fd="goog-tree-expanded-folder-icon",gd="group",hd="gt",id="gu-t-und-latn-k0-qwerty",jd="he",kd="he-t-i0-und",ld="he-t-k0-und",md="head",nd="hi-t-i0-handwrit",od="hi-t-k0-qwerty",pd="hideFocus",qd="hr-t-i0-handwrit",rd="ht-t-i0-handwrit",sd="hu-t-i0-handwrit",td="hu-t-k0-101key",ud="hw",vd="hy-hyr-t-k0-und",wd="hy-hyt-t-k0-und",xd="id-t-i0-handwrit",yd="im",zd="im_t13n",Ad="im_t13n_iw",Bd="image/cleardot.gif",Cd="input_chext_arrow_button_",Dd="inputtool_options_title",Ed="inputtool_select_inputtools",
Fd="inputtool_selected_inputtools",Gd="inputtools",Hd="inscript",Id="is-t-i0-handwrit",Jd="it-t-i0-handwrit",Kd="ita-icon-",Ld="ita-kd-checkbox ita-kd-menuitem-span",Md="ita-kd-img ",Nd="ita-kd-menuitem",Od="ita-kd-menuitem-inputtool-icon ita-kd-menuitem-span ",Pd="ita-kd-menuitem-inputtool-name",Qd="ita-kd-rtl",Rd="iw",Sd="ja-hira-t-i0-und",Td="ja-t-i0-handwrit",Ud="ja-t-ja-hira-i0-und",Vd="k0-und",Wd="ka-t-k0-legacy",Xd="ka-t-k0-und",Yd="key",Zd="keyboards",$d="keydown",ae="keypress",be="keyup",
ce="kn-t-und-latn-k0-und",de="ko-t-i0-handwrit",ee="ky-cyrl-t-k0-und",fe="la-t-i0-handwrit",ge="labelledby",he="latn-002-t-k0-und",ie="left",je="left:",ke="level",le="lt",me="lt-t-i0-handwrit",ne="ltr",oe="lv-t-i0-handwrit",pe="mk-t-i0-handwrit",qe="ml-t-und-latn-k0-und",re="mn-cyrl-t-k0-und",se="mousedown",te="ms-t-i0-handwrit",ue="native code",ve="nb-t-i0-handwrit",we="ne-t-und-latn-k0-und",xe="nl-t-i0-handwrit",ye="nn-t-i0-handwrit",ze="no-t-i0-handwrit",Ae="none",Be="null",Ce="number",De="object",
Ee="off",Fe="on",Ge="or-t-und-latn-k0-und",He="pa-guru-t-k0-und",Ie="pa-guru-t-und-latn-k0-und",Je="pl-t-i0-handwrit",Ke="posinset",Le="presentation",Me="pt",Ne="pt-BR",Oe="pt-PT",Pe="pt-br-t-i0-handwrit",Qe="pt-br-t-k0-und",Re="pt-pt-t-i0-handwrit",Se="pt-pt-t-k0-und",Te="pt-t-i0-handwrit",Ue="px",Ve="px -",We="px 0",Xe='px">',Ye="px}",Ze="quot",$e="right",af="right:",bf="ro-t-i0-handwrit",cf="ro-t-k0-extended",df="ro-t-k0-legacy",ef="role",ff="root",gf="rtl",hf="ru-t-i0-handwrit",jf="sa-t-und-latn-k0-und",
kf="select_remove",lf="selected",mf="setsize",nf="sk-t-i0-handwrit",of="sk-t-k0-qwerty",pf="sl-t-i0-handwrit",qf="splice",rf="sq-t-i0-handwrit",sf="sr-cyrl-t-k0-und",tf="sr-latn-t-k0-und",uf="sr-t-i0-handwrit",vf="string",wf="style",xf='style="-webkit-user-select: none; "',yf="sv-t-i0-handwrit",zf="sw-t-i0-handwrit",Af="ta-t-k0-itrans",Bf="ta-t-k0-ta99",Cf="ta-t-k0-typewriter",Df="ta-t-und-latn-k0-und",Ef="te-t-und-latn-k0-und",Ff="th-t-i0-handwrit",Gf="th-t-k0-pattajoti",Hf="th-t-k0-tis",If="tr-t-i0-handwrit",
Jf="tr-t-k0-lagacy",Kf="tr-t-k0-legacy",Lf="tr-t-k0-und",Mf="tree",Nf="treeitem",Of="true",Pf="type",Qf="uk-t-i0-handwrit",Rf="uk-t-k0-101key",Sf="und-ethi",Tf="und-ethi-t-k0-und",Uf="und-latn-k0-und",Vf="up",Wf="up_down",Xf="us",Yf="uz-cyrl-t-k0-legacy",Zf="uz-cyrl-t-k0-und",$f="uz-latn-t-k0-und",ag="vertical",bg="vi-t-i0-handwrit",cg="vi-t-k0-legacy",dg="vi-t-k0-und",eg="vi-t-k0-viqr",fg="vkd",gg="vkd_",hg="vkd_iw",ig="window",jg="yue-hant",kg="yue-hant-t-i0-und",lg="zh",mg="zh-CN",ng="zh-Hans",
og="zh-Hant",H="zh-TW",pg="zh-cn",qg="zh-hans-t-i0-handwrit",rg="zh-hant-t-i0-cangjie-1982",sg="zh-hant-t-i0-handwrit",tg="zh-hant-t-i0-pinyin",ug="zh-hant-t-i0-und",vg="zh-hk",wg="zh-t-i0-handwrit",xg="zh-t-i0-pinyin",yg="zh-t-i0-wubi-1986",zg="zh-tw",Ag="{background-position:-",Bg="~",Cg="\u0080",Dg="\ufffd";function Eg(a){return function(){return this[a]}}var I;function Fg(a){a.ca=function(){return a.mb?a.mb:a.mb=new a}}
function Gg(a){var b=typeof a;if(b==De)if(a){if(a instanceof ha)return Zb;if(a instanceof Object)return b;var c=Object[B][t][C](a);if(c==Sb)return De;if(c==Qb||typeof a[A]==Ce&&"undefined"!=typeof a[Oa]&&"undefined"!=typeof a[ya]&&!a[ya](qf))return Zb;if(c==Rb||"undefined"!=typeof a[C]&&"undefined"!=typeof a[ya]&&!a[ya](lc))return G}else return Be;else if(b==G&&"undefined"==typeof a[C])return De;return b}function Hg(a){return Gg(a)==Zb}
function Ig(a){var b=Gg(a);return b==Zb||b==De&&typeof a[A]==Ce}function J(a){return typeof a==vf}function Jg(a){var b=typeof a;return b==De&&null!=a||b==G}function Kg(a,b,c){return a[C][Aa](a[xa],arguments)}function Lg(a,b,c){if(!a)throw h();if(2<arguments[A]){var d=ha[B][Ca][C](arguments,2);return function(){var c=ha[B][Ca][C](arguments);ha[B].unshift[Aa](c,d);return a[Aa](b,c)}}return function(){return a[Aa](b,arguments)}}
function K(a,b,c){K=ba[B][xa]&&-1!=ba[B][xa][t]()[y](ue)?Kg:Lg;return K[Aa](null,arguments)}function L(a,b){function c(){}c.prototype=b[B];a.d=b[B];a.prototype=new c}function Mg(a){if(!Ng[Ba](a))return a;-1!=a[y](ab)&&(a=a[p](Og,bb));-1!=a[y](zb)&&(a=a[p](Pg,db));-1!=a[y](Jb)&&(a=a[p](Qg,cb));-1!=a[y](Ua)&&(a=a[p](Rg,eb));return a}
function Sg(a){var b={"&amp;":ab,"&lt;":zb,"&gt;":Jb,"&quot;":Ua},c=da[ra](Ec);return a[p](Tg,function(a,e){var g=b[a];if(g)return g;if(e[oa](0)==$a){var k=Number(vb+e.substr(1));isNaN(k)||(g=ja.fromCharCode(k))}g||(la(c,a+E),g=c[ta].nodeValue[Ca](0,-1));return b[a]=g})}
function Ug(a){return a[p](/&([^;]+);/g,function(a,c){switch(c){case Xb:return ab;case le:return zb;case hd:return Jb;case Ze:return Ua;default:if(c[oa](0)==$a){var d=Number(vb+c.substr(1));if(!isNaN(d))return ja.fromCharCode(d)}return a}})}function Vg(a,b){var c=M(a,b),d;(d=0<=c)&&N[Oa][C](a,c,1);return d}function Wg(a){var b=a[A];if(0<b){for(var c=ha(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Xg(a,b,c,d){N[Oa][Aa](a,Yg(arguments,1))}
function Yg(a,b,c){return 2>=arguments[A]?N[Ca][C](a,b):N[Ca][C](a,b,c)}function Zg(a,b){for(var c in a)b[C](void 0,a[c],c,a)}function $g(a){t:{var b=ah,c;for(c in b)if(b[c]==a){a=!0;break t}a=!1}return a}function bh(a,b){for(var c,d,e=1;e<arguments[A];e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<ch[A];g++)c=ch[g],Object[B].hasOwnProperty[C](d,c)&&(a[c]=d[c])}}
function dh(a){this.code=a;l(this,null);if(0<=this[s][y](lb)){l(this,yd);a=this[s];var b=a[A]-9;0<=b&&a[y](kb,b)==b&&l(this,ud)}else 0<=this[s][y](mb)&&l(this,fg);a=this[s][u](/-t|-i0|-k0/);a[0]==jg&&(a[0]=og);switch(this[s]){case kg:a[0]=og;break;case xg:case yg:a[0]=ng}eh(a[0]);a[1]&&eh(a[1]);if(this[z]==fg)if(fh[this[s]])fh[this[s]][Ca](4);else b=this[s][u](nb),a=b[0],b=b[1],a=a[p](/-/g,Tb),a==Kc&&(a=Xf),0<=M(gh,a)&&(b==Uf||b==Vd)||b==Vd||b.match(/k0-(.*)/)}
function hh(a){if(!a)return null;$g(a)||(a=ih(a));a=a[p](/_/g,ib);$g(a)||(a=ih(a+rb));return jh[a]?jh[a]:$g(a)?(jh[a]=new dh(a),jh[a]):null}function ih(a){if(kh[a])return kh[a];if(a==hg)return ld;if(a==Ad)return kd;if(a==Jf)return Kf;var b=a[u](Tb),b=0==a[Ka](zd,0)?b[2]+ob:2==b[A]?b[1]+pb:0<=M(gh,b[1])?b[2]==Hd?b[1]+pb:b[1]+qb:b[1]+ib+b[2]+pb;return $g(b)?b:a}function eh(a){a!=Sf&&(a=a[u](ib),2!=a[A]||2!=a[1][A]&&a[1][Ca](1))}function lh(){this.b=[]}
function mh(a,b,c){b||(b=[]);a.a=b;a.b=[];if(c)for(b=0;b<c[A];b++)a.a[c[b]]=a.a[c[b]]||[]}function nh(a){var b=oh;if(!a.b[2]){a.b[2]=[];for(var c=0;c<a.a[2][A];c++)a.b[2][c]=new b(a.a[2][c])}return a.b[2]}function ph(a){this.b=[];mh(this,a,[2,3,5,6])}function oh(a){this.b=[];mh(this,a,[])}function qh(a){return a.a[1]}function rh(){return O[Ma]?O[Ma].userAgent:null}function sh(){var a=O[Ha];return a?a.documentMode:void 0}
function P(a){var b;if(!(b=th[a])){b=0;for(var c=ja(uh)[p](/^[\s\xa0]+|[\s\xa0]+$/g,D)[u](sb),d=ja(a)[p](/^[\s\xa0]+|[\s\xa0]+$/g,D)[u](sb),e=ga.max(c[A],d[A]),g=0;0==b&&g<e;g++){var k=c[g]||D,q=d[g]||D,w=RegExp(fb,bd),Sj=RegExp(fb,bd);do{var ea=w.exec(k)||[D,D,D],fa=Sj.exec(q)||[D,D,D];if(0==ea[0][A]&&0==fa[0][A])break;b=((0==ea[1][A]?0:ia(ea[1],10))<(0==fa[1][A]?0:ia(fa[1],10))?-1:(0==ea[1][A]?0:ia(ea[1],10))>(0==fa[1][A]?0:ia(fa[1],10))?1:0)||((0==ea[2][A])<(0==fa[2][A])?-1:(0==ea[2][A])>(0==fa[2][A])?
1:0)||(ea[2]<fa[2]?-1:ea[2]>fa[2]?1:0)}while(0==b)}b=th[a]=0<=b}return b}function vh(a){a=a.className;return J(a)&&a.match(/\S+/g)||[]}function wh(a,b){for(var c=vh(a),d=Yg(arguments,1),e=c[A]+d[A],g=c,k=0;k<d[A];k++)0<=M(g,d[k])||g[x](d[k]);m(a,c[Pa](E));return c[A]==e}function xh(a,b){var c=vh(a),d=Yg(arguments,1),c=yh(c,d);m(a,c[Pa](E))}function yh(a,b){return zh(a,function(a){return!(0<=M(b,a))})}function Ah(a){return a?new Bh(Ch(a)):Dh||(Dh=new Bh)}
function Eh(a){return J(a)?da.getElementById(a):a}function Fh(a,b){Zg(b,function(b,d){d==wf?a[v].cssText=b:d==pc?m(a,b):d==$c?a.htmlFor=b:d in Gh?a[ua](Gh[d],b):0==d[Ka](Yb,0)||0==d[Ka](xc,0)?a[ua](d,b):a[d]=b})}function Hh(a,b,c){return Ih(da,arguments)}
function Ih(a,b){var c=b[0],d=b[1];if(!Jh&&d&&(d.name||d[z])){c=[zb,c];d.name&&c[x](Sa,Mg(d.name),Ua);if(d[z]){c[x](Ta,Mg(d[z]),Ua);var e={};bh(e,d);delete e[z];d=e}c[x](Jb);c=c[Pa](D)}c=a[ra](c);d&&(J(d)?m(c,d):Hg(d)?wh[Aa](null,[c].concat(d)):Fh(c,d));2<b[A]&&Kh(a,c,b,2);return c}
function Kh(a,b,c,d){function e(c){c&&b[ma](J(c)?a.createTextNode(c):c)}for(;d<c[A];d++){var g=c[d];if(!Ig(g)||Jg(g)&&0<g[Da])e(g);else{var k;t:{if(g&&typeof g[A]==Ce){if(Jg(g)){k=typeof g.item==G||typeof g.item==vf;break t}if(Gg(g)==G){k=typeof g.item==G;break t}}k=!1}Lh(k?Wg(g):g,e)}}}function Mh(a,b){Kh(Ch(a),a,arguments,1)}function Nh(a){return a&&a[Na]?a[Na][Ja](a):null}function Ch(a){return 9==a[Da]?a:a.ownerDocument||a[Ha]}function Bh(a){this.a=a||O[Ha]||da}
function Oh(a,b){var c;c=a.a;var d=b&&b!=gb?b.toUpperCase():D;c.querySelectorAll&&c.querySelector&&d?c=c.querySelectorAll(d+D):c=c.getElementsByTagName(d||gb);return c}function Ph(a){var b=Ah(Qh[Ia]),c=null;if(Q){var d=c=b.a.createStyleSheet();Q?d.cssText=a:la(d,a)}else d=Oh(b,md)[0],d||(c=Oh(b,ic)[0],d=b.ga(md),c[Na][pa](d,c)),b=c=b.ga(wf),Q?b.cssText=a:la(b,a),d[ma](c)}
function Rh(a){var b;t:{b=Ch(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.direction||b.getPropertyValue(Bc)||D;break t}b=D}return gf==(b||(a.currentStyle?a.currentStyle.direction:null)||a[v]&&a[v].direction)}function Sh(a){a=Th(a);var b=[];(a=Uh[a])&&Lh(a,function(a){(hh(a.a[1])[z]!=ud||1)&&0<=M(a.a[5],15)||b[x](a.a[1])});return b}function Vh(){var a=[];Zg(Uh,function(b,c){Wh(b,function(a){return 0<=M(a.a[5],15)})||a[x](c)});return a}
function Th(a){a=a[p](/_/g,ib)[Qa]();if(0==a[y](zg)||0==a[y](vg))return og;if(a==lg||0==a[y](pg))return ng;if(a==Me)return Ne;var b=a[u](/[\-]/g),c=D;a=b[0];a==Rd&&(a=jd);Uh[a]&&(c=a);for(var d=1;d<b[A];d++){var e=b[d];2==e[A]?e=e.toUpperCase():4==e[A]&&(e=e[oa](0).toUpperCase()+e[Ca](1));a+=ib+e;Uh[a]&&(c=a)}return c}function Xh(){}function Yh(a){Yh[E](a);return a}function Zh(a,b){l(this,a);this.b=this.v=b}function $h(a,b){a&&ai(this,a,b)}
function ai(a,b,c){var d=l(a,b[z]);Zh[C](a,d);a.v=b.target||b.srcElement;a.b=c;if((c=b.relatedTarget)&&bi)try{Yh(c.nodeName)}catch(e){}a.clientX=void 0!==b.clientX?b.clientX:b.pageX;a.clientY=void 0!==b.clientY?b.clientY:b.pageY;a.q=b[sa]||0;a.wa=b[qa]||(d==ae?b[sa]:0);a.P=b.ctrlKey;a.A=b.altKey;a.Ba=b.shiftKey;a.Ca=b.metaKey;a.ja=b;b.defaultPrevented&&a.J();delete a.a}
function ci(a,b,c,d,e){this.N=a;this.proxy=null;this.src=b;l(this,c);this.capture=!!d;this.ra=e;this.key=++di;this.removed=this.pa=!1}function ei(a){a.removed=!0;a.N=null;a.proxy=null;a.src=null;a.ra=null}function fi(a){this.src=a;this.a={};this.b=0}function gi(a,b){var c=b[z];if(!(c in a.a))return!1;var d=Vg(a.a[c],b);d&&(ei(b),0==a.a[c][A]&&(delete a.a[c],a.b--));return d}function hi(a,b,c,d,e){a=a.a[b];b=-1;a&&(b=ii(a,c,d,e));return-1<b?a[b]:null}
function ii(a,b,c,d){for(var e=0;e<a[A];++e){var g=a[e];if(!g[Fa]&&g.N==b&&g.capture==!!c&&g.ra==d)return e}return-1}
function ji(a,b,c,d,e){if(Hg(b)){for(var g=0;g<b[A];g++)ji(a,b[g],c,d,e);return null}c=ki(c);if(a&&a[li])a=a.m(b,c,d,e);else{if(!b)throw h("Invalid event type");if((g=!!d)&&!mi)a=null;else{var k=a[ni]||(a[ni]=++oi),q=pi[k];q||(pi[k]=q=new fi(a));c=q.add(b,c,!1,d,e);c.proxy||(d=qi(),c.proxy=d,d.src=a,d.N=c,a.addEventListener?a.addEventListener(b,d,g):a.attachEvent(b in ri?ri[b]:ri[b]=Fe+b,d),si[c.key]=c);a=c}}return a}
function qi(){var a=ti,b=mi?function(c){return a[C](b.src,b.N,c)}:function(c){c=a[C](b.src,b.N,c);if(!c)return c};return b}function ui(a,b,c,d,e){if(Hg(b))for(var g=0;g<b[A];g++)ui(a,b[g],c,d,e);else c=ki(c),a&&a[li]?a.Ha(b,c,d,e):a&&(d=!!d,(a=vi(a))&&(b=hi(a,b,c,d,e))&&wi(b))}
function wi(a){if(typeof a==Ce||!a||a[Fa])return!1;var b=a.src;if(b&&b[li])return gi(b.H,a);var c=a[z],d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(c in ri?ri[c]:ri[c]=Fe+c,d);(c=vi(b))?(gi(c,a),0==c.b&&(c.src=null,delete pi[b[ni]||(b[ni]=++oi)])):ei(a);delete si[a.key];return!0}function xi(a,b){var c=a.N,d=a.ra||a.src;a.pa&&wi(a);return c[C](d,b)}
function ti(a,b){if(a[Fa])return!0;if(!mi){var c;if(!(c=b))t:{c=[ig,Qc];for(var d=O,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}c=new $h(c,this);d=!0;return d=xi(a,c)}return xi(a,new $h(b,this))}function vi(a){return a[ni]?pi[a[ni]||(a[ni]=++oi)]||null:null}function ki(a){return Gg(a)==G?a:a[yi]||(a[yi]=function(b){return a[va](b)})}function zi(a){this.b=a;this.a={}}function Ai(a,b){b?a[ua](ef,b):a.removeAttribute(ef)}
function R(a,b,c){Ig(c)&&(c=c[Pa](E));var d=Yb+b;if(c===D||void 0==c)Bi||(Bi={atomic:!1,autocomplete:Ae,dropeffect:Ae,haspopup:!1,live:Ee,multiline:!1,multiselectable:!1,orientation:ag,readonly:!1,relevant:Vb,required:!1,sort:Ae,busy:!1,disabled:!1,hidden:!1,invalid:Tc}),c=Bi,b in c?a[ua](d,c[b]):a.removeAttribute(d);else a[ua](d,c)}
function Ci(a,b,c,d,e){if(!(Q||S&&P(wb)))return!0;if(Di&&e)return Ei(a);if(e&&!d||!c&&(17==b||18==b||Di&&91==b))return!1;if(S&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(Q&&d&&b==a)return!1;switch(a){case 13:return!(Q&&Q&&9<=Fi);case 27:return!S}return Ei(a)}
function Ei(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||S&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function Gi(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}}function Hi(a,b){null!=a&&this.g[Aa](this,arguments)}
function T(){this.H=new fi(this);this.tb=this}function Ii(a,b){var c,d=a.oa;if(d){c=[];for(var e=1;d;d=d.oa)c[x](d),++e}var d=a.tb,e=b,g=e[z]||e;if(J(e))e=new Zh(e,d);else if(e instanceof Zh)e.v=e.v||d;else{var k=e,e=new Zh(g,d);bh(e,k)}var k=!0,q;if(c)for(var w=c[A]-1;!e.a&&0<=w;w--)q=e.b=c[w],k=Ji(q,g,!0,e)&&k;e.a||(q=e.b=d,k=Ji(q,g,!0,e)&&k,e.a||(k=Ji(q,g,!1,e)&&k));if(c)for(w=0;!e.a&&w<c[A];w++)q=e.b=c[w],k=Ji(q,g,!1,e)&&k;return k}
function Ji(a,b,c,d){b=a.H.a[b];if(!b)return!0;b=Wg(b);for(var e=!0,g=0;g<b[A];++g){var k=b[g];if(k&&!k[Fa]&&k.capture==c){var q=k.N,w=k.ra||k.src;k.pa&&gi(a.H,k);e=!1!==q[C](w,d)&&e}}return e&&!1!=d.i}function Ki(){}function Li(a){T[C](this);this.i=a||Ah();this.qa=Mi}function Ni(a,b){if(a==b)throw h(Pb);if(b&&a.s&&a.T&&a.s.r&&a.T&&(a.T in a.s.r&&a.s.r[a.T])&&a.s!=b)throw h(Pb);a.s=b;Li.d.Na[C](a,b)}
function Oi(a,b,c){if(a.f)throw h(Lb);a.e||a.ha();b?b[pa](a.e,c||null):a.i.a[Ia][ma](a.e);a.s&&!a.s.f||a.u()}function Pi(a){null==a.qa&&(a.qa=Rh(a.f?a.e:a.i.a[Ia]));return a.qa}function U(a){return!!a.k&&0!=a.k[A]}function Qi(a){return a.k?a.k[A]:0}function V(a,b){return a.k?a.k[b]||null:null}function W(a,b){a.k&&Lh(a.k,b,void 0)}function X(a,b,c){Li[C](this,c);this.h=b||Ri;this.V=a}
function Si(a,b){if(b!=a.na){a.na=b;var c=Ti(a);if(c){var d=ga.max(0,(a.M()-1)*a.h.Ja)+Ue;Pi(a)?c[v].paddingRight=d:c[v].paddingLeft=d}W(a,function(a){Si(a,b+1)})}}function Y(a){var b=a[r]();b&&Ui(b,a)}function Vi(a,b){if(a.Ma!=b){a.Ma=b;Wi(a);var c=a.c();c&&(R(c,lf,b),b&&(c=a[r]().c(),R(c,Ub,a.B())))}}function Xi(a,b){var c=a[r](),c=!c.da||c==a[n]()&&0?a.h.hb:a.h.gb,d=a.n()&&U(a);b.g(Eb,a.h.Cb,Va,a.B(),Ya,Yi(a),Eb,c,Wa,$b+Zi(a)+yb,d?D:Dc,Ya);d&&W(a,function(a){Xi(a,b)});b.g(Bb)}
function Yi(a){var b=new Hi;b.g(Eb,a.fa(),Xa,Pi(a)?af:je,ga.max(0,(a.M()-1)*a.h.Ja),Xe,a.ib(),Gb+a.ia()+Za,$i(a),Ab);return b[t]()}function $i(a){var b=new Hi;b.g(Fb,a.h.Eb,Ua,D,Jb,a.V,Cb,Ib,D,Cb);return b[t]()}
function aj(a){var b=a[r](),b=!b.da||b==a[n]()&&!1,c=a.h,d=new Hi;d.g(c.U,E,c.ub,E);if(U(a)){var e=0,e=a.n()?2:1;b||(e=a.o?e+8:e+4);switch(e){case 1:d.g(c.yb);break;case 2:d.g(c.xb);break;case 4:d.g(c.bb);break;case 5:d.g(c.wb);break;case 6:d.g(c.vb);break;case 8:d.g(c.cb);break;case 9:d.g(c.Ab);break;case 10:d.g(c.zb);break;default:d.g(c.ab)}}else b?d.g(c.ab):a.o?d.g(c.cb):d.g(c.bb);return d[t]()}function Zi(a){return(a.o?(a.M()-1)*a.h.Ja:jb)+We}function Ti(a){return(a=a.c())?a[ta]:null}
function bj(a){return(a=Ti(a))&&a.lastChild?a.lastChild.previousSibling:null}function cj(a){return(a=a.c())?a.lastChild:null}function dj(a){return-1!=a.V[y](ab)?Fc in O?Sg(a.V):Ug(a.V):a.V}function Wi(a){var b=Ti(a);b&&m(b,a.fa())}function ej(a,b){b.v[La](Pf)==Rc&&U(a)?a.G(!a.n()):(Y(a),Wi(a))}function fj(a){return a.n()&&U(a)?fj(V(a,Qi(a)-1)):a}function gj(a,b){a.b!=b&&(a.b=b,hj(b,a),W(a,function(a){gj(a,b)}))}
function ij(a){T[C](this);this.a=a;a=Q?Zc:gc;this.b=ji(this.a,Q?Yc:Wc,this,!Q);this.i=ji(this.a,a,this,!Q)}function jj(a,b){T[C](this);a&&(this.va&&kj(this),this.W=a,this.ta=ji(this.W,ae,this,b),this.Oa=ji(this.W,$d,this.Gb,b,this),this.va=ji(this.W,be,this.Hb,b,this))}function kj(a){a.ta&&(wi(a.ta),wi(a.Oa),wi(a.va),a.ta=null,a.Oa=null,a.va=null);a.W=null;a.t=-1;a.I=-1}function lj(a,b,c,d){d&&ai(this,d,void 0);l(this,Yd);this.q=a;this.wa=b}
function mj(a){if(typeof a.Ra==G)return a.Ra();if(J(a))return a[u](D);if(Ig(a)){for(var b=[],c=a[A],d=0;d<c;d++)b[x](a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}function nj(a){if(typeof a.Ia==G)return a.Ia();if(typeof a.Ra!=G){if(Ig(a)||J(a)){var b=[];a=a[A];for(var c=0;c<a;c++)b[x](c);return b}var b=[],c=0,d;for(d in a)b[c++]=d;return b}}function oj(a,b,c){X[C](this,a,b,c)}function pj(a){this.j={};if(a){var b=nj(a);a=mj(a);for(var c=0;c<b[A];c++)this.set(b[c],a[c])}}
function qj(a,b,c,d){for(var e=0;e<b[A];e++){var g=b[oa](e);a.j[g]||(a.j[g]=new pj);a=a.j[g]}if(d&&void 0!==a.C)throw h('The collection already contains the key "'+b+Ua);a.C=c}function rj(a,b){void 0!==a.C&&b[x](a.C);for(var c in a.j)rj(a.j[c],b)}function sj(a,b,c){void 0!==a.C&&c[x](b);for(var d in a.j)sj(a.j[d],b+d,c)}function tj(){this.a=new pj}function uj(a,b){var c=!1,d=a.a.Ia(b);d&&d[A]&&(a.S=0,a.aa=0,c=a.a.get(d[0]),c=vj(a,c))&&(a.Aa=d);return c}
function vj(a,b){var c;b&&(a.S<b[A]&&(c=b[a.S],a.ka=b),c&&(c.Qa(),Y(c)));return!!c}function Z(a,b,c){X[C](this,a,b,c);this.ea=!0;Vi(this,!0);this.l=this;this.$=new tj;if(Q)try{da.execCommand(Kb,!1,!0)}catch(d){}}function Ui(a,b){if(a.l!=b){var c=!1;a.l&&(c=null==a.l,Vi(a.l,!1));if(a.l=b)Vi(b,!0),c&&Y(b);Ii(a,mc)}}function wj(a){!1!=a.da&&(a.da=!1,a.f&&xj(a))}
function xj(a){function b(a){var k=cj(a);if(k){var q=!d||c==a[n]()&&!e?a.h.hb:a.h.gb;m(k,q);(k=a.sa())&&m(k,aj(a))}W(a,b)}var c=a,d=c.da,e=!0;b(a)}function yj(a){if(!1!=a.L){a.L=!1;if(a.f){var b=Ti(a);b&&m(b,a.fa())}a.l==a&&V(a,0)&&Ui(a,V(a,0))}}function hj(a,b){var c=a.$,d=dj(b);if(d&&!/^[\s\xa0]*$/[Ba](null==d?D:ja(d))){var d=d[Qa](),e=c.a.get(d);e?e[x](b):c.a.set(d,[b])}}function zj(){}
function Aj(){this.b={};this.i=aa[Ma][Ga]||F;zj.ca();this.a=ca;this.a[Ea][ng]=ca[Ea][mg];this.a[Ea][og]=ca[Ea][H]}function Bj(a,b,c){var d=a.a[Ea][a.i];d||(d=a.a[Ea].en);for(var e=0;e<d[A];e++){var g=d[e][u](xb),k=a.b[Th(g[1])];k&&0!=k[A]&&b({language:g[0],inputtools:k},c)}}function Cj(a){Dj.ita_icon_style||(Dj.ita_icon_style=!0,Ej());a=Fj[a];(a=Kd+(a?null!=a.a[4]?a.a[4]:-1:0))&&(a=Md+a);return a||D}
function Ej(){var a=D;Zg(Fj,function(b){b=null!=b.a[4]?b.a[4]:-1;a+=tb+b+Ag+(50*(b%10)+14)+Ve+(50*ga.floor(b/10)+17)+Ye});Ph(a)}function Gj(){}function Hj(a){return Hh(Ob,{"class":nc+a[Qa](),id:Cd+a[Qa]()})}function Ij(){}function Jj(a,b){var c=da.getElementById(a),d=chrome.i18n.getMessage(b);c&&(c.innerText=d)}function Kj(){this.a=Lj;Mj(this)}
function Mj(a){var b=Nj(a),c=Oj(a),d=f.getItem(Zd);d&&Lh(d[u](hb),function(a){if(a=hh(gg+a))a=a[s],0<=M(b,a)||b[x](a)});d=f.getItem(uc);!c&&d&&(d=hh(gg+d))&&(c=d[s]);f&&(f[a.a.fb]=b[Pa](hb));f&&(f[a.a.eb]=c)}function Pj(a){if(f){var b=f.getItem(a);if(b)return(a=hh(b))?a[s]:b}return D}function Nj(a){var b=Pj(a.a.fb);a=[];b&&(a=b[u](hb));for(b=0;b<a[A];b++)a[b]=hh(a[b])[s];return a}function Oj(a){return(a=Pj(a.a.eb))?hh(a)[s]:D}function Qj(a,b,c){Z[C](this,a,b,c)}
function Rj(a,b){this.Q=new Aj;Tj||(Tj=new Gj);this.i=b||Kj.ca();Uj||(Uj=new Ij);a||zj.ca();this.Y=new zi(this);aa[Ha].title=chrome.i18n.getMessage(Dd);Jj(Dd,Dd);Jj(Ed,Ed);Jj(Fd,Fd);var c=Oj(this.i),c=Vj[Ba](c)?gf:ne;Fh(da[Ia],{dir:c});var c=Hj($e),d=Hj(ie),e=Hj(Vf),g=Hj(Gc);this.Y.m(c,qc,this.Za).m(d,qc,this.$a).m(e,qc,K(this.Ya,this,-1)).m(g,qc,K(this.Ya,this,1));Mh(Eh(kf),c,Hh(jc),d);Mh(Eh(Wf),e,Hh(jc),g);c=Ri;c.Kb=Bd;c.ya=D;c.xa=D;c.za=D;this.b=new Qj(ff,c);yj(this.b);wj(this.b);d=this.b;e=K(this.Wa,
this);g=K(this.Za,this);d.Sa=e;d.Ta=g;this.a=new Qj(ff,c);yj(this.a);wj(this.a);c=this.a;d=K(this.Xa,this);e=K(this.$a,this);c.Sa=d;c.Ta=e;Wj(this);t:{c=Nj(this.i);if(0==c[A]&&(c=Sh(navigator[Ga]),!c))break t;for(d=0;d<c[A];d++)this.Z({inputtool:c[d]},this.a)}Oi(this.b,Eh(Gd));Oi(this.a,Eh(lf));$($e,Cc);$(ie,Cc);$(Vf,Cc);$(Gc,Cc)}function Xj(a,b){for(var c=a.a[na](),d=0;d<c[A];d++)if(c[d].K==b)return c[d];return null}
function Yj(a){for(var b=[],c=a.a[na](),d=0;d<c[A];d++)b[x](c[d].K);(a=Oj(a.i))&&!(0<=M(b,a))&&f&&(f.current_input=D);f&&(f.input_tools=b[Pa]());chrome.extension.sendRequest({ua:!0})}function Wj(a){var b=Vh();Lh(b,function(a){var b=Sh(a);Lh(b,function(b){var d=this.Q;d.b[a]=d.b[a]||[];d.b[a][x](b)},this)},a);b=K(a.Z,a);Bj(a.Q,b,a.b)}function $(a,b){ka(Eh(Cd+a[Qa]())[v],b==Lc?fc:Ae)}var O=this,ni="closure_uid_"+(1E9*ga.random()>>>0),oi=0;
ba[B].bind=ba[B][xa]||function(a,b){if(1<arguments[A]){var c=ha[B][Ca][C](arguments,1);c.unshift(this,a);return K[Aa](null,c)}return K(this,a)};var Og=/&/g,Pg=/</g,Qg=/>/g,Rg=/\"/g,Ng=/[&<>\"]/,Tg=/&([^;\s<&]+);?/g;var N=ha[B],M=N[y]?function(a,b,c){return N[y][C](a,b,c)}:function(a,b,c){c=null==c?0:0>c?ga.max(0,a[A]+c):c;if(J(a))return J(b)&&1==b[A]?a[y](b,c):-1;for(;c<a[A];c++)if(c in a&&a[c]===b)return c;return-1},Lh=N.forEach?function(a,b,c){N.forEach[C](a,b,c)}:function(a,b,c){for(var d=a[A],e=J(a)?a[u](D):a,g=0;g<d;g++)g in e&&b[C](c,e[g],g,a)},zh=N.filter?function(a,b,c){return N.filter[C](a,b,c)}:function(a,b,c){for(var d=a[A],e=[],g=0,k=J(a)?a[u](D):a,q=0;q<d;q++)if(q in k){var w=k[q];b[C](c,w,q,a)&&
(e[g++]=w)}return e},Wh=N.every?function(a,b,c){return N.every[C](a,b,c)}:function(a,b,c){for(var d=a[A],e=J(a)?a[u](D):a,g=0;g<d;g++)if(g in e&&!b[C](c,e[g],g,a))return!1;return!0};var ch="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var ah={Vc:"zh-hans-t-i0-cangjie-1982",Xc:"zh-hans-t-i0-cangjie-1987",Wc:rg,Yc:"zh-hant-t-i0-cangjie-1987",Zc:kg,$c:xg,ad:tg,bd:"am-t-i0-und",cd:"ar-t-i0-und",dd:"be-t-i0-und",ed:"bn-t-i0-und",fd:"bg-t-i0-und",hd:"en-t-i0-und",gd:"nl-t-i0-und",jd:"fr-t-i0-und",kd:"de-t-i0-und",ld:"el-t-i0-und",md:"gu-t-i0-und",nd:kd,od:"hi-t-i0-und",pd:Sd,qd:"it-t-i0-und",rd:Ud,sd:"kn-t-i0-und",td:"ml-t-i0-und",ud:"mr-t-i0-und",vd:"ne-t-i0-und",wd:"or-t-i0-und",xd:"fa-t-i0-und",yd:"pl-t-i0-und",zd:"pt-t-i0-und",Ad:"pa-t-i0-und",
Bd:"ru-t-i0-und",Cd:"sa-t-i0-und",Dd:"sr-t-i0-und",Ed:"si-t-i0-und",Fd:"es-t-i0-und",Gd:"ta-t-i0-und",Hd:"te-t-i0-und",Id:"ti-t-i0-und",Jd:"tr-t-i0-und",Kd:"uk-t-i0-und",Ld:"ur-t-i0-und",Md:"vi-t-i0-und",Nd:yg,Od:ug,Qd:"sq-t-k0-und",Rd:"ar-t-k0-und",Sd:vd,Td:wd,Ud:"eu-t-k0-und",Vd:"be-t-k0-und",Wd:"bn-t-k0-und",Xd:hc,Yd:"bs-t-k0-und",Zd:Qe,$d:"bg-t-k0-und",ae:ec,be:"ca-t-k0-und",ce:"chr-t-k0-und",de:oc,ee:"hr-t-k0-und",fe:"cs-t-k0-und",ge:tc,he:"da-t-k0-und",ie:"prs-t-k0-und",je:od,ke:"nl-t-k0-und",
le:"dz-t-k0-und",me:"en-t-k0-und",ne:Ic,oe:"et-t-k0-und",pe:Tf,qe:"fi-t-k0-und",re:"fr-t-k0-und",se:"gl-t-k0-und",te:Xd,ue:Wd,ve:"de-t-k0-und",we:"el-t-k0-und",xe:"gu-t-k0-und",ye:id,ze:He,Ae:Ie,Be:ld,Ce:"hi-t-k0-und",De:td,Ee:"is-t-k0-und",Fe:"it-t-k0-und",Ge:"kn-t-k0-und",He:ce,Ie:"kk-t-k0-und",Je:"km-t-k0-und",Ke:"ko-t-k0-und",Le:ee,Me:"lo-t-k0-und",Ne:"lv-t-k0-und",Oe:"lt-t-k0-und",Pe:"mk-t-k0-und",Qe:"ml-t-k0-und",Re:qe,Se:"mt-t-k0-und",We:"my-t-k0-und",Te:"mi-t-k0-und",Ue:re,Ve:"srp-t-k0-und",
Ze:"no-t-k0-und",$e:"or-t-k0-und",af:Ge,bf:he,cf:"ps-t-k0-und",df:"fa-t-k0-und",ef:"pl-t-k0-und",ff:Se,gf:"rom-t-k0-und",hf:"ro-t-k0-und",jf:df,kf:cf,lf:"ru-t-k0-und",mf:jf,nf:sf,of:tf,pf:"si-t-k0-und",qf:"sk-t-k0-und",rf:of,sf:"sl-t-k0-und",tf:"uzs-t-k0-und",uf:Nc,vf:"sv-t-k0-und",wf:zc,xf:Bf,yf:"ta-t-k0-und",Af:Df,Bf:Cf,zf:Af,Cf:"tt-t-k0-und",Df:"te-t-k0-und",Ef:Ef,Ff:"th-t-k0-und",Gf:Gf,Hf:Hf,If:Kf,Jf:Lf,Kf:"ug-t-k0-und",Lf:Rf,Mf:"ur-t-k0-und",Of:Zf,Pf:Yf,Qf:$f,Rf:dg,Sf:cg,Tf:eg,Uf:"vi-t-k0-vni",
Vf:"yi-t-k0-und",Xe:"ne-t-k0-und",Ye:we,Nf:Jc,Tb:Wb,Wb:ac,Xb:dc,Yb:kc,cc:sc,Tc:vc,dc:wc,lc:Ac,fc:Hc,Mc:Mc,gc:Oc,Vb:Pc,ic:Uc,hc:Vc,jc:ad,rc:cd,kc:dd,nc:nd,bc:qd,mc:rd,oc:sd,qc:xd,pc:Id,sc:Jd,tc:Td,uc:de,vc:fe,xc:me,wc:oe,yc:pe,zc:te,Bc:ve,ec:xe,Cc:ye,Ac:ze,Dc:Je,Ec:Te,Fc:Pe,Gc:Re,Hc:bf,Ic:hf,Kc:nf,Lc:pf,Ub:rf,Jc:uf,Oc:yf,Nc:zf,Pc:Ff,Qc:If,Rc:Qf,Sc:bg,Zb:wg,$b:qg,ac:sg};var jh={},gh="bn gu pa kn ml or sa ta te ne".split(" "),kh={im_pinyin_zh_hans:xg,im_wubi_zh_hans:yg,im_pinyin_zh_hant:tg,im_zhuyin_zh_hant:ug,im_t13n_ja:Ud,"im_t13n_ja-Hira":Sd,vkd_en_dvorak:Ic,vkd_hy_east:vd,vkd_hy_west:wd,vkd_bg_phone:ec,vkd_cs_qwertz:tc,vkd_deva_phone:od,vkd_ethi:Tf,vkd_ka_qwerty:Xd,vkd_ka_typewriter:Wd,vkd_guru_inscript:He,vkd_guru_phone:Ie,vkd_gu_phone:id,vkd_hu_101:td,vkd_ro_sr13392_primary:df,vkd_ro_sr13392_secondary:cf,vkd_sk_qwerty:of,vkd_es_es:Nc,vkd_ta_tamil99:Bf,vkd_ta_typewriter:Cf,
vkd_ta_itrans:Af,vkd_tr_f:Kf,vkd_tr_q:Lf,vkd_uk_101:Rf,vkd_uz_cyrl_phone:Zf,vkd_uz_cyrl_type:Yf,vkd_vi_tcvn:dg,vkd_vi_telex:cg,vkd_vi_viqr:eg,vkd_chr_phone:oc,vkd_th_pattajoti:Gf,vkd_th_tis:Hf},Zj={},ak;for(ak in kh)Zj[kh[ak]]=ak;var fh=Zj;dh[B].toString=Eg("code");lh[B].toString=function(){return this.a[t]()};L(ph,lh);ph[B].B=function(){return this.a[0]};L(oh,lh);var Fj={},bk={},Uh={};
Lh([[1,"am-t-i0-und",[["am","\u12a0\u121b\u122d\u129b"]],["am"],16,,["im_t13n_am"]],[2,"ar-t-i0-und",[["ar","\u0627\u0644\u0639\u0631\u0628\u064a\u0629"]],["ar"],2,,["im_t13n_ar"]],[3,"bn-t-i0-und",[["bn","\u09ac\u09be\u0982\u09b2\u09be"]],["bn"],3,,["im_t13n_bn"]],[4,xg,[[mg,"\u62fc\u97f3"]],[mg],29,,["im_pinyin_zh_hans"]],[6,"el-t-i0-und",[["el","\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"]],["el"],23,,["im_t13n_el"]],[7,"gu-t-i0-und",[["gu","\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0"]],["gu"],
4,,["im_t13n_gu"]],[8,"hi-t-i0-und",[["hi","\u0939\u093f\u0928\u094d\u0926\u0940"]],["hi"],5,,["im_t13n_hi"]],[9,kd,[[jd,"\u05e2\u05b4\u05d1\u05b0\u05e8\u05b4\u05d9\u05ea"]],[jd],20,,["im_t13n_he",Ad]],[10,Ud,[["ja","\u65e5\u672c\u8a9e"]],["ja"],28,,["im_t13n_ja"]],[11,"kn-t-i0-und",[["kn","\u0c95\u0ca8\u0ccd\u0ca8\u0ca1"]],["kn"],6,,["im_t13n_kn"]],[12,"ml-t-i0-und",[["ml","\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02"]],["ml"],7,,["im_t13n_ml"]],[13,"mr-t-i0-und",[["mr","\u092e\u0930\u093e\u0920\u0940"]],
["mr"],9,,["im_t13n_mr"]],[14,"ne-t-i0-und",[["ne","\u0928\u0947\u092a\u093e\u0932\u0940"]],["ne"],8,,["im_t13n_ne"]],[15,"or-t-i0-und",[["or","\u0b13\u0b21\u0b3c\u0b3f\u0b06"]],["or"],19,,["im_t13n_or"]],[16,"fa-t-i0-und",[["fa","\u0641\u0627\u0631\u0633\u06cc"]],["fa"],14,,["im_t13n_fa"]],[17,"pa-t-i0-und",[["pa","\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40"]],["pa"],10,,["im_t13n_pa"]],[46,"pl-t-i0-und",[["pl","Polski"]],,37,,["im_t13n_pl"]],[18,"ru-t-i0-und",[["ru","\u0420\u0443\u0441\u0441\u043a\u0438\u0439"]],
["ru"],24,,["im_t13n_ru"]],[19,"sa-t-i0-und",[["sa","\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d"]],["sa"],15,,["im_t13n_sa"]],[20,"sr-t-i0-und",[["sr","C\u0440\u043f\u0441\u043a\u0438"]],["sr"],22,,["im_t13n_sr"]],[21,"si-t-i0-und",[["si","\u0dc3\u0dd2\u0d82\u0dc4\u0dbd"]],["si"],18,,["im_t13n_si"]],[22,"ta-t-i0-und",[["ta","\u0ba4\u0bae\u0bbf\u0bb4\u0bcd"]],["ta"],11,,["im_t13n_ta"]],[23,"te-t-i0-und",[["te","\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41"]],["te"],12,,["im_t13n_te"]],[24,"ti-t-i0-und",
[["ti","\u1275\u130d\u122d\u129b"]],["ti"],17,,["im_t13n_ti"]],[25,"ur-t-i0-und",[["ur","\u0627\u0631\u062f\u0648"]],["ur"],13,,["im_t13n_ur"]],[26,yg,[[mg,"\u4e94\u7b14"]],[mg],30,,["im_wubi_zh_hans"]],[27,tg,[[H,"\u6f22\u8a9e\u62fc\u97f3"]],[H],29,,["im_pinyin_zh_hant"]],[28,ug,[[H,"\u6ce8\u97f3"]],[H],31,,["im_zhuyin_zh_hant"]],[30,"vi-t-i0-und",[["vi","Ti\u1ebfng Vi\u1ec7t"]],["vi"],21,,["im_t13n_vi"]],[34,"be-t-i0-und",[["be","\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f"]],["be"],
26,,["im_t13n_be"]],[35,"bg-t-i0-und",[["bg","\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438"]],["bg"],27,,["im_t13n_bg"]],[36,"uk-t-i0-und",[["uk","\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430"]],["uk"],25,,["im_t13n_uk"]],[37,"de-t-i0-und",[["de","Deutsch"]],["de"],35],[38,"es-t-i0-und",[["es","Espa\u00f1ol"]],["es"],34],[39,"fr-t-i0-und",[["fr","Fran\u00e7ais"]],["fr"],36],[40,"it-t-i0-und",[["it","Italiano"]],["it"],39],[41,"nl-t-i0-und",[["nl",Nb]],["nl"],40],[42,"pt-t-i0-und",
[[Ne,"Portugu\u00eas"]],[Ne,Oe],38],[43,rg,[[H,"\u5009\u9821"]],[H],32],[44,kg,[[H,"\u5ee3\u6771\u8a71"]],[H],33],[101,"sq-t-k0-und",[["sq","shqip"]],["sq"],0,,["vkd_sq"]],[102,"ar-t-k0-und",[["ar","\u0644\u0648\u062d\u0629 \u0645\u0641\u0627\u062a\u064a\u062d \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629"]],["ar"],0,,["vkd_ar"]],[103,vd,[["hy","\u0531\u0580\u0587\u0565\u056c\u0561\u0570\u0561\u0575\u0565\u0580\u0565\u0576"]],["hy"],0,,["vkd_hy_east"]],[104,wd,[["hy","\u0531\u0580\u0565\u0582\u0574\u057f\u0561\u0570\u0561\u0575\u0565\u0580\u0567\u0576"]],
["hy"],0,,["vkd_hy_west"]],[105,"eu-t-k0-und",[["eu","Euskara"]],["eu"],0,,["vkd_eu"]],[106,"be-t-k0-und",[["be","\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f"]],["be"],0,,["vkd_be"]],[107,"bn-t-k0-und",[["bn","\u09ac\u09be\u0982\u09b2\u09be (INSCRIPT)"]],["bn"],0,,["vkd_bn_inscript"]],[108,hc,[["bn","\u09ac\u09be\u0982\u09b2\u09be (\u09ab\u09cb\u09a8\u09c7\u099f\u09bf\u0995)"]],["bn"],0,,["vkd_bn_phone"]],[109,"bs-t-k0-und",[["bs","bosanski"]],["bs"],0,,["vkd_bs"]],[110,Qe,[["pt-br",
"portugu\u00eas brasileiro"]],[Ne],0,,["vkd_pt_br"]],[111,"bg-t-k0-und",[["bg","\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a"]],["bg"],0,,["vkd_bg"]],[112,ec,[["bg","\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a (\u0444\u043e\u043d\u0435\u0442\u0438\u043a\u0430)"]],["bg"],0,,["vkd_bg_phone"]],[113,"ca-t-k0-und",[["ca","catal\u00e0"]],["ca"],0,,["vkd_ca"]],[114,"chr-t-k0-und",[["chr","\u13e3\u13b3\u13a9"]],["chr"],0,,["vkd_chr"]],
[115,"hr-t-k0-und",[["hr","hrvatski"]],["hr"],0,,["vkd_hr"]],[116,"cs-t-k0-und",[["cs","\u010de\u0161tina"]],["cs"],0,,["vkd_cs"]],[117,tc,[["cs","\u010de\u0161tina QWERTZ"]],["cs"],0,,["vkd_cs_qwertz"]],[118,"da-t-k0-und",[["da","dansk"]],["da"],0,,["vkd_da"]],[119,"prs-t-k0-und",[["prs","\u0641\u0627\u0631\u0633\u06cc \u062f\u0631\u06cc"]],["prs","fa"],0,,["vkd_prs"]],[120,"nl-t-k0-und",[["nl",Nb]],["nl"],0,,["vkd_nl"]],[121,od,[["hi","\u0926\u0947\u0935\u0928\u093e\u0917\u0930\u0940 (\u092b\u094b\u0928\u0947\u091f\u093f\u0915)"]],
["hi","mr"],0,,["vkd_deva_phone"]],[122,"en-t-k0-und",[[F,"English Keyboard"]],[F],0,,["vkd_en"]],[123,"et-t-k0-und",[["et","eesti keel"]],["et"],0,,["vkd_et"]],[124,Tf,[["am","\u130d\u12d5\u12dd"]],["am","ti"],0,,["vkd_ethi"]],[125,"fi-t-k0-und",[["fi","suomi"]],["fi"],0,,["vkd_fi"]],[126,"fr-t-k0-und",[["fr","fran\u00e7ais"]],["fr","ht"],0,,["vkd_fr"]],[127,"gl-t-k0-und",[["gl","Galego"]],["gl"],0,,["vkd_gl"]],[128,Xd,[["ka","\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8 (\u10e5\u10ec\u10d4\u10e0\u10e2\u10e7)"]],
["ka"],0,,["vkd_ka_qwerty"]],[129,Wd,[["ka","\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8 (\u10e1\u10d0\u10d1\u10d4\u10ed\u10d3\u10d8 \u10db\u10d0\u10dc\u10e5\u10d0\u10dc\u10d0)"]],["ka"],0,,["vkd_ka_typewriter"]],[130,"de-t-k0-und",[["de","Deutsch"]],["de"],0,,["vkd_de"]],[131,"el-t-k0-und",[["el","\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"]],["el"],0,,["vkd_el"]],[132,"gu-t-k0-und",[["gu","\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0 (INSCRIPT)"]],["gu"],0,,["vkd_gu_inscript"]],[133,id,[["gu",
"\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0 (\u0aab\u0acb\u0aa8\u0ac7\u0aa4\u0abf\u0a95)"]],["gu"],0,,["vkd_gu_phone"]],[134,He,[["pa-guru","\u0a17\u0a41\u0a30\u0a2e\u0a41\u0a16\u0a40 (INSCRIPT)"]],["pa"],0,,["vkd_guru_inscript"]],[135,Ie,[["pa-guru","\u0a17\u0a41\u0a30\u0a2e\u0a41\u0a16\u0a40 (\u0a2b\u0a4b\u0a28\u0a47\u0a1f\u0a3f\u0a15)"]],["pa"],0,,["vkd_guru_phone"]],[136,ld,[[jd,"\u05e2\u05b4\u05d1\u05b0\u05e8\u05b4\u05d9\u05ea"]],[jd],0,,["vkd_he",hg]],[137,"hi-t-k0-und",[["hi","\u0939\u093f\u0928\u094d\u0926\u0940"]],
["hi"],0,,["vkd_hi"]],[138,td,[["hu","magyar nyelv (101)"]],["hu"],0,,["vkd_hu_101"]],[139,"is-t-k0-und",[["is","\u00edslenska"]],["is"],0,,["vkd_is"]],[140,"it-t-k0-und",[["it","italiano"]],["it"],0,,["vkd_it"]],[141,"kn-t-k0-und",[["kn","\u0c95\u0ca8\u0ccd\u0ca8\u0ca1 (INSCRIPT)"]],["kn"],0,,["vkd_kn_inscript"]],[142,ce,[["kn","\u0c95\u0ca8\u0ccd\u0ca8\u0ca1 (\u0cab\u0cca\u0ca8\u0cc6\u0c9f\u0cbf\u0c95\u0ccd)"]],["kn"],0,,["vkd_kn_phone"]],[143,"kk-t-k0-und",[["kk","\u049a\u0430\u0437\u0430\u049b"]],
["kk"],0,,["vkd_kk"]],[144,"km-t-k0-und",[["km","\u17a2\u1780\u17d2\u179f\u179a\u1781\u17d2\u1798\u17c2\u179a NiDA"]],["km"],0,,["vkd_km"]],[145,"ko-t-k0-und",[["ko","\ud55c\uad6d\uc5b4"]],["ko"],0,,["vkd_ko"]],[146,ee,[["ky","\u041a\u044b\u0440\u0433\u044b\u0437"]],["ky"],0,,["vkd_ky_cyrl"]],[147,"lo-t-k0-und",[["lo","\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7"]],["lo"],0,,["vkd_lo"]],[148,"lv-t-k0-und",[["lv","latvie\u0161u valoda"]],["lv"],0,,["vkd_lv"]],[149,"lt-t-k0-und",[[le,"lietuvi\u0173 kalba"]],
[le],0,,["vkd_lt"]],[150,"mk-t-k0-und",[["mk","\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438"]],["mk"],0,,["vkd_mk"]],[151,"ml-t-k0-und",[["ml","\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02 (INSCRIPT)"]],["ml"],0,,["vkd_ml_inscript"]],[152,qe,[["ml","\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02 (\u0d2b\u0d4a\u0d23\u0d31\u0d4d\u0d31\u0d3f\u0d15\u0d4d)"]],["ml"],0,,["vkd_ml_phone"]],[153,"mt-t-k0-und",[["mt","Malti"]],["mt"],0,,["vkd_mt"]],[154,"mi-t-k0-und",[["mi","M\u0101ori"]],["mi"],0,,["vkd_mi"]],
[155,re,[["mn","\u041c\u043e\u043d\u0433\u043e\u043b"]],["mn"],0,,["vkd_mn_cyrl"]],[156,"srp-t-k0-und",[["sr","Crnogorski jezik"]],["sr"],0,,["vkd_srp"]],[157,"no-t-k0-und",[["no","norsk"]],["no"],0,,["vkd_no"]],[158,"or-t-k0-und",[["or","\u0b13\u0b21\u0b3c\u0b3f\u0b06 (INSCRIPT)"]],["or"],0,,["vkd_or_inscript"]],[159,Ge,[["or","\u0b13\u0b21\u0b3c\u0b3f\u0b06 (\u0b2b\u0b4b\u0b28\u0b47\u0b1f\u0b3f\u0b15)"]],["or"],0,,["vkd_or_phone"]],[160,he,[[F,"Africa Latin"]],"af cy ga id jw ms sw tl".split(" "),
0,,["vkd_latn_002"]],[161,"ps-t-k0-und",[["ps","\u067e\u069a\u062a\u0648"]],["ps"],0,,["vkd_ps"]],[162,"fa-t-k0-und",[["fa","\u0641\u0627\u0631\u0633\u06cc"]],["fa"],0,,["vkd_fa"]],[163,"pl-t-k0-und",[["pl","polski"]],["pl"],0,,["vkd_pl"]],[164,Se,[["pt-pt","portugu\u00eas europeu"]],[Oe],0,,["vkd_pt_pt"]],[165,"rom-t-k0-und",[["rom","rromani \u0107hib"]],["rom"],0,,["vkd_rom"]],[166,"ro-t-k0-und",[["ro","rom\u00e2n\u0103"]],["ro"],0,,["vkd_ro"]],[167,df,[["ro","rom\u00e2n\u0103 SR13392 Primary"]],
["ro"],0,,["vkd_ro_sr13392_primary"]],[168,cf,[["ro","rom\u00e2n\u0103 SR13392 Secondary"]],["ro"],0,,["vkd_ro_sr13392_secondary"]],[169,"ru-t-k0-und",[["ru","\u0420\u0443\u0441\u0441\u043a\u0430\u044f \u043a\u043b\u0430\u0432\u0438\u0430\u0442\u0443\u0440\u0430"]],["ru"],0,,["vkd_ru"]],[170,jf,[["sa","\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d (\u092b\u094b\u0928\u0947\u091f\u093f\u0915\u094d)"]],["sa"],0,,["vkd_sa_phone"]],[171,sf,[["sr","\u0421\u0440\u043f\u0441\u043a\u0438"]],["sr"],
0,,["vkd_sr_cyrl"]],[172,tf,[["sr","Srpski"]],["sr"],0,,["vkd_sr_latn"]],[173,"si-t-k0-und",[["si","\u0dc1\u0dd4\u0daf\u0dca\u0db0 \u0dc3\u0dd2\u0d82\u0dc4\u0dbd SLS1134"]],["si"],0,,["vkd_si"]],[174,"sk-t-k0-und",[["sk","slovensk\u00fd jazyk"]],["sk"],0,,["vkd_sk"]],[175,of,[["sk","slovensk\u00fd jazyk - QWERTY"]],["sk"],0,,["vkd_sk_qwerty"]],[176,"sl-t-k0-und",[["sl","sloven\u0161\u010dina"]],["sl"],0,,["vkd_sl"]],[177,"uzs-t-k0-und",[["uzs","Southern Uzbek"]],["uzs"],0,,["vkd_uzs"]],[178,Nc,[["es",
"espa\u00f1ol"]],["es"],0,,["vkd_es_es"]],[179,"sv-t-k0-und",[["sv","svenska"]],["sv"],0,,["vkd_sv"]],[180,zc,[["de","Deutschsprachige Schweiz"]],["de"],0,,["vkd_de_ch"]],[181,Bf,[["ta","\u0ba4\u0bae\u0bbf\u0bb4\u0bcd (TAMIL99)"]],["ta"],0,,["vkd_ta_tamil99"]],[182,"ta-t-k0-und",[["ta","\u0ba4\u0bae\u0bbf\u0bb4\u0bcd (INSCRIPT)"]],["ta"],0,,["vkd_ta_inscript"]],[183,Df,[["ta","\u0ba4\u0bae\u0bbf\u0bb4\u0bcd (\u0baa\u0bcb\u0ba9\u0bc6\u0b9f\u0bbf\u0b95\u0bcd)"]],["ta"],0,,["vkd_ta_phone"]],[205,Cf,
[["ta","\u0ba4\u0bae\u0bbf\u0bb4\u0bcd (TYPE-WRITER)"]],["ta"],0],[206,Af,[["ta","\u0ba4\u0bae\u0bbf\u0bb4\u0bcd (ITRANS)"]],["ta"],0],[184,"tt-t-k0-und",[["tt","\u0422\u0430\u0442\u0430\u0440"]],["tt"],0,,["vkd_tt"]],[185,"te-t-k0-und",[["te","\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41 (INSCRIPT)"]],["te"],0,,["vkd_te_inscript"]],[186,Ef,[["te","\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41 (\u0c2b\u0c4b\u0c28\u0c46\u0c1f\u0c3f\u0c15\u0c4d)"]],["te"],0,,["vkd_te_phone"]],[187,"th-t-k0-und",[["th","\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22"]],
["th"],0,,["vkd_th"]],[204,Gf,[["th","\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22 (Pattajoti)"]],["th"],0],[203,Hf,[["th","\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22 (TIS-820.2538)"]],["th"],0],[188,Kf,[["tr","T\u00fcrk\u00e7e - F"]],["tr"],0,,["vkd_tr_f",Jf]],[189,Lf,[["tr","T\u00fcrk\u00e7e - Q"]],["tr"],0,,["vkd_tr_q"]],[190,"ug-t-k0-und",[["ug","\u0626\u06c7\u064a\u063a\u06c7\u0631\u0686\u06d5"]],["ug"],0,,["vkd_ug"]],[191,Rf,[["uk","\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u044c\u043a\u0430 \u043c\u043e\u0301\u0432\u0430 (101)"]],
["uk"],0,,["vkd_uk_101"]],[192,"ur-t-k0-und",[["ur","\u0627\u0631\u062f\u0648"]],["ur"],0,,["vkd_ur"]],[193,$f,[["uz","O\u2018zbek"]],["uz"],0,,["vkd_uz_latn"]],[194,Zf,[["uz","\u040e\u0437\u0431\u0435\u043a (\u0444\u043e\u043d\u0435\u0442\u0438\u0447\u043d\u0456)"]],["uz"],0,,["vkd_uz_cyrl_phone"]],[195,Yf,[["uz","\u040e\u0437\u0431\u0435\u043a (\u0420\u043e\u0441\u0456\u0439\u0441\u044c\u043a\u0430)"]],["uz"],0,,["vkd_uz_cyrl_type"]],[196,dg,[["vi","Ti\u1ebfng Vi\u1ec7t TCVN 6064"]],["vi"],0,,["vkd_vi_tcvn"]],
[197,cg,[["vi","Ti\u1ebfng Vi\u1ec7t Telex"]],["vi"],0,,["vkd_vi_telex"]],[198,eg,[["vi","Ti\u1ebfng Vi\u1ec7t VIQR"]],["vi"],0,,["vkd_vi_viqr"]],[208,"vi-t-k0-vni",[["vi","Ti\u1ebfng Vi\u1ec7t VNI"]],["vi"],0],[199,"dz-t-k0-und",[["dz","\u0f62\u0fab\u0f7c\u0f44\u0f0b\u0f41\u0f0b"]],["dz"],0,,["vkd_dz"]],[200,Ic,[[F,"English Dvorak Keyboard"]],[F],0],[201,oc,[["chr","\u13e3\u13b3\u13a9 \u13d7\u13a7\u13c1\u13a2\u13cd\u13d7 \u13da\u13c3\u13f4\u13ac"]],["chr"],0,,["vkd_chr_phone"]],[202,"my-t-k0-und",
[["my","\u1019\u103c\u1014\u103a\u1019\u102c\u1018\u102c\u101e\u102c"]],["my"],0,,["vkd_my"]],[5,"en-t-i0-und",[[F,"English"]],,41,,["im_t13n_en"]],[29,Sd,[["ja","\u65e5\u672c\u8a9e"]],,-1,,["im_t13n_ja_hira"]],[45,"tr-t-i0-und",[["tr","T\u00fcrk"]],,42],[207,"yi-t-k0-und",[["yi","\u05d4\u05e2\u05d1\u05e8\u05e2\u05d9\u05d9 \u05d9\u05d9\u05b4\u05d3\u05d9\u05e9 \u05e7\u05d9\u05d1\u05d0\u05b8\u05e8\u05d3"]],["yi"],0],[209,"ne-t-k0-und",[["ne","\u0928\u0947\u092a\u093e\u0932\u0940 (\u091f\u094d\u0930\u092f\u093e\u0921\u093f\u0938\u0928\u0932)"]],
["ne"],0],[210,we,[["ne","\u0928\u0947\u092a\u093e\u0932\u0940 (\u0930\u094b\u092e\u093e\u0928\u093e\u0907\u091c\u094d\u0921)"]],["ne"],0],[211,Jc,[[F,"US International"]],["nl","fr","de","it",Ne,Oe,"es"],0],[401,Wb,[["af","Afrikaans"]],["af"],1,[17,5,13,12,14]],[402,ac,[["be","\u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f"]],["be"],1,[17,5,13,12,14]],[403,dc,[["bg","\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438"]],["bg"],1,[17,5,13,12,14]],[404,kc,[["ca","catal\u00e0"]],["ca"],
1,[17,5,13,12,14]],[405,sc,[["cs","\u010de\u0161tina"]],["cs"],1,[17,5,13,12,14]],[406,vc,[["cy","Cymraeg"]],["cy"],1,[17,5,13,12,14]],[407,wc,[["da","dansk"]],["da"],1,[17,5,13,12,14]],[408,Ac,[["de","Deutsch"]],["de"],1,[17,5,13,12,14]],[409,Hc,[[F,"English"]],[F],1,[17,5,13,12,14]],[410,Mc,[["es","espa\u00f1ol"]],["es"],1,[17,5,13,12,14]],[411,Oc,[["et","eesti"]],["et"],1,[17,5,13,12,14]],[412,Pc,[["eu","euskara"]],["eu"],1,[17,5,13,12,14]],[413,Uc,[["fi","suomi"]],["fi"],1,[17,5,13,12,14]],[414,
Vc,[["fil","Filipino"]],["fil"],1,[17,5,13,12,14]],[415,ad,[["fr","fran\u00e7ais"]],["fr"],1,[17,5,13,12,14]],[416,cd,[["ga","Gaeilge"]],["ga"],1,[17,5,13,12,14]],[417,dd,[["gl","galego"]],["gl"],1,[17,5,13,12,14]],[453,nd,[["hi","\u0939\u093f\u0928\u094d\u0926\u0940"]],["hi"],1,[17,5,13,12,14]],[418,qd,[["hr","hrvatski"]],["hr"],1,[17,5,13,12,14]],[419,rd,[["ht","Haitian"]],["ht"],1,[17,5,13,12,14]],[420,sd,[["hu","magyar"]],["hu"],1,[17,5,13,12,14]],[421,xd,[["id","Bahasa Indonesia"]],["id"],1,
[17,5,13,12,14]],[422,Id,[["is","\u00edslenska"]],["is"],1,[17,5,13,12,14]],[423,Jd,[["it","italiano"]],["it"],1,[17,5,13,12,14]],[424,Td,[["ja","\u65e5\u672c\u8a9e"]],["ja"],1,[17,5,13,12,14]],[425,de,[["ko","\ud55c\uad6d\uc5b4"]],["ko"],1,[17,5,13,12,14]],[426,fe,[["la","Latin"]],["la"],1,[17,5,13,12,14]],[427,me,[[le,"lietuvi\u0173"]],[le],1,[17,5,13,12,14]],[428,oe,[["lv","latvie\u0161u"]],["lv"],1,[17,5,13,12,14]],[429,pe,[["mk","\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438"]],
["mk"],1,[17,5,13,12,14]],[430,te,[["ms","Bahasa Melayu"]],["ms"],1,[17,5,13,12,14]],[431,ve,[["nb","norsk bokm\u00e5l"]],["nb"],1,[17,5,13,12,14]],[432,xe,[["nl",Nb]],["nl"],1,[17,5,13,12,14]],[434,ye,[["nn","nynorsk"]],["nn"],1,[17,5,13,12,14]],[433,ze,[["no","norsk"]],["no"],1,[17,5,13,12,14]],[435,Je,[["pl","polski"]],["pl"],1,[17,5,13,12,14]],[436,Te,[[Ne,"portugu\u00eas"]],,1,[17,5,13,12,14]],[437,Pe,[[Ne,"portugu\u00eas (Brasil)"]],[Ne],1,[17,5,13,12,14]],[438,Re,[[Oe,"portugu\u00eas (Portugal)"]],
[Oe],1,[17,5,13,12,14]],[439,bf,[["ro","rom\u00e2n\u0103"]],["ro"],1,[17,5,13,12,14]],[440,hf,[["ru","\u0440\u0443\u0441\u0441\u043a\u0438\u0439"]],["ru"],1,[17,5,13,12,14]],[441,nf,[["sk","sloven\u010dina"]],["sk"],1,[17,5,13,12,14]],[442,pf,[["sl","sloven\u0161\u010dina"]],["sl"],1,[17,5,13,12,14]],[443,rf,[["sq","shqip"]],["sq"],1,[17,5,13,12,14]],[444,uf,[["sr","\u0421\u0440\u043f\u0441\u043a\u0438"]],["sr"],1,[17,5,13,12,14]],[445,yf,[["sv","svenska"]],["sv"],1,[17,5,13,12,14]],[446,zf,[["sw",
"Kiswahili"]],["sw"],1,[17,5,13,12,14]],[454,Ff,[["th","\u0e44\u0e17\u0e22"]],["th"],1,[17,5,13,12,14]],[447,If,[["tr","T\u00fcrk\u00e7e"]],["tr"],1,[17,5,13,12,14]],[448,Qf,[["uk","\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430"]],["uk"],1,[17,5,13,12,14]],[449,bg,[["vi","Ti\u1ebfng Vi\u1ec7t"]],["vi"],1,[17,5,13,12,14]],[450,wg,[[mg,"\u4e2d\u6587"]],,1,[17,5,13,12,14]],[451,qg,[[mg,"\u4e2d\u6587\uff08\u7b80\u4f53\u4e2d\u6587\uff09"]],[mg],1,[17,5,13,12,14]],[452,sg,[[H,"\u4e2d\u6587\uff08\u7e41\u9ad4\u4e2d\u6587\uff09"]],
[H],1,[17,5,13,12,14]]],function(a){var b=new ph(a);if(a=b.a[1]){Fj[a]=b;var c=qh(nh(b)[0]);c&&(bk[a]=c)}Lh(b.a[3],function(a){a==H?a=og:a==mg&&(a=ng);Uh[a]||(Uh[a]=[]);Uh[a][x](b)})});var ck,dk,ek,fk;fk=ek=dk=ck=!1;var gk;if(gk=rh()){var hk=O[Ma];ck=0==gk[Ka]("Opera",0);dk=!ck&&(-1!=gk[y]("MSIE")||-1!=gk[y]("Trident"));ek=!ck&&-1!=gk[y]("WebKit");fk=!ck&&!ek&&!dk&&"Gecko"==hk.product}var ik=ck,Q=dk,bi=fk,S=ek,jk=O[Ma],Di=-1!=(jk&&jk.platform||D)[y]("Mac"),kk;
t:{var lk=D,mk;if(ik&&O.opera)var nk=O.opera.version,lk=typeof nk==G?nk():nk;else if(bi?mk=/rv\:([^\);]+)(\)|;)/:Q?mk=/\b(?:MSIE|rv)\s+([^\);]+)(\)|;)/:S&&(mk=/WebKit\/(\S+)/),mk)var ok=mk.exec(rh()),lk=ok?ok[1]:D;if(Q){var pk=sh();if(pk>parseFloat(lk)){kk=ja(pk);break t}}kk=lk}var uh=kk,th={},qk=O[Ha],Fi=qk&&Q?sh()||("CSS1Compat"==qk.compatMode?ia(uh,10):5):void 0;var Dh,Jh=!Q||Q&&9<=Fi,rk=!bi&&!Q||Q&&Q&&9<=Fi||bi&&P("1.9.1");Q&&P("9");var Gh={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:ef,rowspan:"rowSpan",type:Pf,usemap:"useMap",valign:"vAlign",width:"width"};I=Bh[B];I.c=function(a){return J(a)?this.a.getElementById(a):a};I.ga=function(a,b,c){return Ih(this.a,arguments)};I.Fb=Mh;I.removeNode=Nh;I.getChildren=function(a){return rk&&void 0!=a.children?a.children:zh(a[wa],function(a){return 1==a[Da]})};
I.contains=function(a,b){if(a[za]&&1==b[Da])return a==b||a[za](b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b[Na];return b==a};!Q||P(9);Xh[B].lb=!1;Xh[B].ba=function(){this.lb||(this.lb=!0,this.p())};Xh[B].p=function(){if(this.nb)for(;this.nb[A];)this.nb.shift()()};Yh[E]=function(){};var mi=!Q||Q&&9<=Fi,sk=Q&&!P("9");!S||P("528");bi&&P("1.9b")||Q&&P("8")||ik&&P("9.5")||S&&P("528");bi&&!P("8")||Q&&P("9");Zh[B].ba=function(){};Zh[B].a=!1;Zh[B].i=!0;Zh[B].J=function(){this.i=!1};L($h,Zh);I=$h[B];I.v=null;I.clientX=0;I.clientY=0;I.q=0;I.wa=0;I.P=!1;I.A=!1;I.Ba=!1;I.Ca=!1;I.ja=null;I.J=function(){$h.d.J[C](this);var a=this.ja;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,sk)try{if(a.ctrlKey||112<=a[sa]&&123>=a[sa])a.keyCode=-1}catch(b){}};var li="closure_listenable_"+(1E6*ga.random()|0),di=0;fi[B].add=function(a,b,c,d,e){var g=this.a[a];g||(g=this.a[a]=[],this.b++);var k=ii(g,b,d,e);-1<k?(a=g[k],c||(a.pa=!1)):(a=new ci(b,this.src,a,!!d,e),a.pa=c,g[x](a));return a};fi[B].remove=function(a,b,c,d){if(!(a in this.a))return!1;var e=this.a[a];b=ii(e,b,c,d);return-1<b?(ei(e[b]),N[Oa][C](e,b,1),0==e[A]&&(delete this.a[a],this.b--),!0):!1};fi[B].removeAll=function(a){var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d[A];e++)++b,ei(d[e]);delete this.a[c];this.b--}return b};var si={},pi={},ri={},yi="__closure_events_fn_"+(1E9*ga.random()>>>0);L(zi,Xh);var tk=[];I=zi[B];I.m=function(a,b,c,d,e){Hg(b)||(tk[0]=b,b=tk);for(var g=0;g<b[A];g++){var k=ji(a,b[g],c||this,d||!1,e||this.b||this);if(!k)break;this.a[k.key]=k}return this};I.Ha=function(a,b,c,d,e){if(Hg(b))for(var g=0;g<b[A];g++)this.Ha(a,b[g],c,d,e);else e=e||this.b||this,c=ki(c||this),d=!!d,b=a&&a[li]?hi(a.H,b,c,d,e):a?(a=vi(a))?hi(a,b,c,d,e):null:null,b&&(wi(b),delete this.a[b.key]);return this};I.removeAll=function(){Zg(this.a,wi);this.a={}};I.p=function(){zi.d.p[C](this);this.removeAll()};
I.handleEvent=function(){throw h("EventHandler.handleEvent not implemented");};var Vj=RegExp("^(ar|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)","i");var Bi;I=Hi[B];I.O=D;I.set=function(a){this.O=D+a};I.g=function(a,b,c){this.O+=a;if(null!=b)for(var d=1;d<arguments[A];d++)this.O+=arguments[d];return this};I.clear=function(){this.O=D};I.toString=Eg("O");L(T,Xh);T[B][li]=!0;I=T[B];I.oa=null;I.Na=function(a){this.oa=a};I.removeEventListener=function(a,b,c,d){ui(this,a,b,c,d)};I.p=function(){T.d.p[C](this);this.H&&this.H.removeAll(void 0);this.oa=null};I.m=function(a,b,c,d){return this.H.add(a,b,!1,c,d)};I.Ha=function(a,b,c,d){return this.H.remove(a,b,c,d)};Fg(Ki);Ki[B].a=0;Ki.ca();L(Li,T);Li[B].Bb=Ki.ca();var Mi=null;I=Li[B];I.T=null;I.f=!1;I.e=null;I.qa=null;I.K=null;I.s=null;I.k=null;I.r=null;I.B=function(){return this.T||(this.T=xb+(this.Bb.a++)[t](36))};I.c=Eg("e");I.getParent=Eg("s");I.Na=function(a){if(this.s&&this.s!=a)throw h("Method not supported");Li.d.Na[C](this,a)};I.ha=function(){this.e=this.i.a[ra](Ec)};I.u=function(){this.f=!0;W(this,function(a){!a.f&&a.c()&&a.u()})};I.F=function(){W(this,function(a){a.f&&a.F()});this.a&&this.a.removeAll();this.f=!1};
I.p=function(){this.f&&this.F();this.a&&(this.a.ba(),delete this.a);W(this,function(a){a.ba()});this.e&&Nh(this.e);this.s=this.K=this.e=this.r=this.k=null;Li.d.p[C](this)};
I.Ga=function(a,b,c){if(a.f&&(c||!this.f))throw h(Lb);if(0>b||b>Qi(this))throw h("Child component index out of bounds");this.r&&this.k||(this.r={},this.k=[]);if(a[n]()==this){var d=a.B();this.r[d]=a;Vg(this.k,a)}else{var d=this.r,e=a.B();if(e in d)throw h('The object already contains the key "'+e+Ua);d[e]=a}Ni(a,this);Xg(this.k,b,0,a);a.f&&this.f&&a[n]()==this?(c=this.e,c[pa](a.c(),c[wa][b]||null)):c?(this.e||this.ha(),b=V(this,b+1),Oi(a,this.e,b?b.e:null)):this.f&&(!a.f&&a.e&&a.e[Na]&&1==a.e[Na][Da])&&
a.u()};I.X=function(a,b){if(a){var c=J(a)?a:a.B();a=this.r&&c?(c in this.r?this.r[c]:void 0)||null:null;if(c&&a){var d=this.r;c in d&&delete d[c];Vg(this.k,a);b&&(a.F(),a.e&&Nh(a.e));Ni(a,null)}}if(!a)throw h("Child is not in parent component");return a};L(X,Li);var uk={};I=X[B];I.Ma=!1;I.ea=!1;I.na=-1;I.p=function(){X.d.p[C](this);this.b&&(this.b.removeNode(this),this.b=null);this.e=null};I.ma=function(){var a=this.c();if(a){var b=bj(this);b&&!b.id&&(b.id=this.B()+ub);Ai(a,Nf);R(a,lf,!1);R(a,Sc,!1);R(a,ke,this.M());b&&R(a,ge,b.id);(a=this.la())&&Ai(a,Le);(a=this.sa())&&Ai(a,Le);if(a=cj(this))if(Ai(a,gd),a.hasChildNodes())for(a=Qi(this),b=1;b<=a;b++){var c=V(this,b-1).c();R(c,mf,a);R(c,Ke,b)}}};
I.ha=function(){var a=new Hi;Xi(this,a);var b;b=this.i.a;var c=a[t](),a=b[ra](Ec);Q?(la(a,Db+c),a[Ja](a[ta])):la(a,c);if(1==a[wa][A])b=a[Ja](a[ta]);else for(b=b.createDocumentFragment();a[ta];)b[ma](a[ta]);this.e=b};I.u=function(){X.d.u[C](this);uk[this.B()]=this;this.ma()};I.F=function(){X.d.F[C](this);delete uk[this.B()]};
I.Ga=function(a,b){a[n]();var c=V(this,b-1),d=V(this,b);X.d.Ga[C](this,a,b);a.D=c;a.o=d;c?c.o=a:this.Ua=a;d?d.D=a:this.Va=a;var e=this[r]();e&&gj(a,e);Si(a,this.M()+1);if(this.c()&&(this.R(),this.n())){e=cj(this);a.c()||a.ha();var g=a.c(),k=d&&d.c();e[pa](g,k);this.f&&a.u();d||(c?c.R():(ka(e[v],D),this.G(this.n())))}};I.add=function(a,b){b&&b[n]();a[n]()&&a[n]().X(a);this.Ga(a,b?this.k&&b?M(this.k,b):-1:Qi(this));return a};
I.X=function(a){var b=this[r](),c=b?b.l:null;if(c==a||a[za](c))if(b.hasFocus()){Y(this);c=this.sb;if(Gg(c)==G)this&&(c=K(c,this));else if(c&&typeof c[va]==G)c=K(c[va],c);else throw h("Invalid listener argument");O.setTimeout(c,10)}else Y(this);X.d.X[C](this,a);this.Va==a&&(this.Va=a.D);this.Ua==a&&(this.Ua=a.o);a.D&&(a.D.o=a.o);a.o&&(a.o.D=a.D);c=!a.o;a.b=null;a.na=-1;if(b&&(b.removeNode(this),this.f)){b=cj(this);if(a.f){var d=a.c();b[Ja](d);a.F()}c&&(c=V(this,Qi(this)-1))&&c.R();U(this)||(ka(b[v],
Ae),this.R(),m(this.la(),this.ia()))}return a};I.remove=X[B].X;I.sb=function(){Y(this)};I.M=function(){var a=this.na;0>a&&(a=(a=this[n]())?a.M()+1:0,Si(this,a));return a};I.contains=function(a){for(;a;){if(a==this)return!0;a=a[n]()}return!1};I.getChildren=function(){var a=[];W(this,function(b){a[x](b)});return a};I.n=Eg("ea");
I.G=function(a){var b=a!=this.ea;if(!b||Ii(this,a?cc:bc)){var c;this.ea=a;c=this[r]();var d=this.c();if(U(this)){if(!a&&(c&&this[za](c.l))&&Y(this),d){if(c=cj(this))if(ka(c[v],a?D:Ae),a&&this.f&&!c.hasChildNodes()){var e=new Hi;W(this,function(a){Xi(a,e)});la(c,e[t]());W(this,function(a){a.u()})}this.R()}}else(c=cj(this))&&ka(c[v],Ae);d&&(m(this.la(),this.ia()),R(d,Sc,a));b&&Ii(this,a?Rc:rc)}};I.Qa=function(){var a=this[n]();a&&(a.G(!0),a.Qa())};
I.fa=function(){return this.h.Jb+(this.Ma?E+this.h.Ib:D)};I.ib=function(){return Hb+aj(this)+Za};I.c=function(){var a=X.d.c[C](this);a||(this.e=a=this.i.c(this.B()));return a};I.sa=function(){var a=Ti(this);return a?a[ta]:null};I.la=function(){var a=Ti(this);return a?a[wa][1]:null};I.R=function(){var a=this.sa();a&&m(a,aj(this));if(a=cj(this))a[v].backgroundPosition=Zi(this)};L(ij,T);ij[B].handleEvent=function(a){var b=new $h(a.ja);l(b,a[z]==Yc||a[z]==Wc?Yc:Zc);Ii(this,b)};ij[B].p=function(){ij.d.p[C](this);wi(this.b);wi(this.i);delete this.a};L(jj,T);I=jj[B];I.W=null;I.ta=null;I.Oa=null;I.va=null;I.t=-1;I.I=-1;I.Ka=!1;
var vk={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},wk={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},xk=Q||S&&P(wb),yk=Di&&bi;I=jj[B];
I.Gb=function(a){S&&(17==this.t&&!a.P||18==this.t&&!a.A||Di&&91==this.t&&!a.Ca)&&(this.I=this.t=-1);-1==this.t&&(a.P&&17!=a.q?this.t=17:a.A&&18!=a.q?this.t=18:a.Ca&&91!=a.q&&(this.t=91));if(xk&&!Ci(a.q,this.t,a.Ba,a.P,a.A))this[va](a);else this.I=bi?Gi(a.q):a.q,yk&&(this.Ka=a.A)};I.Hb=function(a){this.I=this.t=-1;this.Ka=a.A};
I.handleEvent=function(a){var b=a.ja,c,d,e=b.altKey;Q&&a[z]==ae?(c=this.I,d=13!=c&&27!=c?b[sa]:0):S&&a[z]==ae?(c=this.I,d=0<=b[qa]&&63232>b[qa]&&Ei(c)?b[qa]:0):ik?(c=this.I,d=Ei(c)?b[sa]:0):(c=b[sa]||this.I,d=b[qa]||0,yk&&(e=this.Ka),Di&&(63==d&&224==c)&&(c=191));var g=c,k=b.keyIdentifier;c?63232<=c&&c in vk?g=vk[c]:25==c&&a.Ba&&(g=9):k&&k in wk&&(g=wk[k]);this.t=g;a=new lj(g,d,0,b);a.A=e;Ii(this,a)};I.c=Eg("W");I.p=function(){jj.d.p[C](this);kj(this)};L(lj,$h);L(oj,X);oj[B].b=null;oj[B].getTree=function(){if(this.b)return this.b;var a=this[n]();return a&&(a=a[r]())?(gj(this,a),a):null};oj[B].ia=function(){var a=this.n();if(a&&this.Q)return this.Q;if(!a&&this.La)return this.La;var b=this.h;if(U(this)){if(a&&b.ya)return b.U+E+b.ya;if(!a&&b.xa)return b.U+E+b.xa}else if(b.za)return b.U+E+b.za;return D};I=pj[B];I.C=void 0;I.set=function(a,b){qj(this,a,b,!1)};I.add=function(a,b){qj(this,a,b,!0)};I.get=function(a){for(var b=this,c=0;c<a[A];c++){var d=a[oa](c);if(!b.j[d])return;b=b.j[d]}return b.C};I.Ra=function(){var a=[];rj(this,a);return a};I.Ia=function(a){var b=[];if(a){for(var c=this,d=0;d<a[A];d++){var e=a[oa](d);if(!c.j[e])return[];c=c.j[e]}sj(c,a,b)}else sj(this,D,b);return b};I.clear=function(){this.j={};this.C=void 0};
I.remove=function(a){for(var b=this,c=[],d=0;d<a[A];d++){var e=a[oa](d);if(!b.j[e])throw h('The collection does not have the key "'+a+Ua);c[x]([b,e]);b=b.j[e]}a=b.C;for(delete b.C;0<c[A];){e=c.pop();b=e[0];e=e[1];t:{var d=b.j[e].j,g=void 0;for(g in d){d=!1;break t}d=!0}if(d)delete b.j[e];else break}return a};I=tj[B];I.w=D;I.Aa=null;I.ka=null;I.aa=0;I.S=0;I.clear=function(){this.w=D};L(Z,X);I=Z[B];I.Ea=null;I.Da=null;I.Pa=!1;I.da=!0;I.L=!0;I.getTree=function(){return this};I.M=function(){return 0};I.Qa=function(){};I.qb=function(){this.Pa=!0;wh(this.c(),Xc);this.l&&Y(this.l)};I.pb=function(){this.Pa=!1;xh(this.c(),Xc)};I.hasFocus=Eg("Pa");I.n=function(){return!this.L||Z.d.n[C](this)};I.G=function(a){this.L?Z.d.G[C](this,a):this.ea=a};I.ib=function(){return D};I.la=function(){var a=Ti(this);return a?a[ta]:null};I.sa=function(){return null};I.R=function(){};
I.fa=function(){return Z.d.fa[C](this)+(this.L?D:E+this.h.Db)};I.ia=function(){var a=this.n();if(a&&this.Q)return this.Q;if(!a&&this.La)return this.La;var b=this.h;return a&&b.kb?b.U+E+b.kb:!a&&b.jb?b.U+E+b.jb:D};I.ma=function(){Z.d.ma[C](this);var a=this.c();Ai(a,Mf);R(a,ge,bj(this).id)};
I.u=function(){Z.d.u[C](this);var a=this.c();m(a,this.h.ob);a[ua](pd,Of);a=this.c();a.tabIndex=0;var b=this.Ea=new jj(a),c=this.Da=new ij(a);(this.a||(this.a=new zi(this))).m(c,Zc,this.pb).m(c,Yc,this.qb).m(b,Yd,this.rb).m(a,se,this.Fa).m(a,qc,this.Fa).m(a,yc,this.Fa);this.ma()};I.F=function(){Z.d.F[C](this);this.Ea.ba();this.Ea=null;this.Da.ba();this.Da=null};
I.Fa=function(a){var b;t:{b=null;for(var c=a.v;null!=c;){if(b=uk[c.id])break t;if(c==this.c())break;c=c[Na]}b=null}if(b)switch(a[z]){case se:ej(b,a);break;case qc:a.J();break;case yc:a.v[La](Pf)==Rc&&U(b)||b.G(!b.n())}};
I.rb=function(a){var b=!1,b=this.$,c=!1;switch(a.q){case 40:case 38:if(a.P){var c=40==a.q?1:-1,d=b.Aa;if(d){var e=null,g=!1;if(b.ka){var k=b.S+c;0<=k&&k<b.ka[A]?(b.S=k,e=b.ka):g=!0}e||(k=b.aa+c,0<=k&&k<d[A]&&(b.aa=k),d[A]>b.aa&&(e=b.a.get(d[b.aa])),e&&(e[A]&&g)&&(b.S=-1==c?e[A]-1:0));vj(b,e)&&(b.Aa=d)}c=!0}break;case 8:d=b.w[A]-1;c=!0;0<d?(b.w=b.w.substring(0,d),uj(b,b.w)):0==d?b.w=D:c=!1;break;case 27:b.w=D,c=!0}if(!(b=c)){if(b=this.l){b=this.l;c=!0;switch(a.q){case 39:if(a.A)break;U(b)&&(b.n()?
Y(V(b,0)):b.G(!0));break;case 37:if(a.A)break;U(b)&&b.n()?b.G(!1):(d=b[n](),e=b[r](),d&&(e.L||d!=e)&&Y(d));break;case 40:t:if(U(b)&&b.n())d=V(b,0);else{for(d=b;d!=b[r]();){e=d.o;if(null!=e){d=e;break t}d=d[n]()}d=null}d&&Y(d);break;case 38:d=b.D;null!=d?d=fj(d):(d=b[n](),e=b[r](),d=e.L||d!=e?d:null);d&&Y(d);break;default:c=!1}c&&(a.J(),(e=b[r]())&&e.$.clear());b=c}b||(b=this.$,c=!1,a.P||a.A||(d=ja.fromCharCode(a.wa||a.q)[Qa](),(1==d[A]&&d>=E&&d<=Bg||d>=Cg&&d<=Dg)&&(d!=E||b.w)&&(b.w+=d,c=uj(b,b.w))),
b=c)}b&&a.J();return b};I.createNode=function(a){return new oj(a||D,this.h,this.i)};I.removeNode=function(a){var b=this.$,c=dj(a);if(c&&!/^[\s\xa0]*$/[Ba](null==c?D:ja(c))){var c=c[Qa](),d=b.a.get(c);d&&(Vg(d,a),d[A]&&b.a.remove(c))}};
var Ri={Ja:19,ob:"goog-tree-root goog-tree-item",Db:"goog-tree-hide-root",Cb:"goog-tree-item",gb:"goog-tree-children",hb:"goog-tree-children-nolines",Jb:"goog-tree-row",Eb:"goog-tree-item-label",U:"goog-tree-icon",ub:"goog-tree-expand-icon",yb:"goog-tree-expand-icon-plus",xb:"goog-tree-expand-icon-minus",Ab:"goog-tree-expand-icon-tplus",zb:"goog-tree-expand-icon-tminus",wb:"goog-tree-expand-icon-lplus",vb:"goog-tree-expand-icon-lminus",cb:"goog-tree-expand-icon-t",bb:"goog-tree-expand-icon-l",ab:"goog-tree-expand-icon-blank",
ya:fd,xa:ed,za:"goog-tree-file-icon",kb:fd,jb:ed,Ib:lf};Fg(zj);var Qh=aa[Ha],Dj=aa;Ah(aa[Ha]);new T;var Tj=null;var Uj=null;var Lj={Sb:"gp",Nb:"ra",gg:Vf,hg:"ua",bg:"si",cg:"ss",fg:"ui",$f:"ri",Ob:"ds",Pb:"dr",Mb:"ai",ag:"sq",Lb:"aq",URL:"url",Yf:"pl",Uc:"hd",dg:"su",Zf:"re",Rb:"gl",Qb:"gi",Xf:"lo",Wf:"ki",fb:"input_tools",eb:"current_input",Pd:"current_input_state",eg:"tvk"};Fg(Kj);L(Qj,Z);Qj[B].u=function(){Qj.d.u[C](this);var a=this.c();(this.a||(this.a=new zi(this))).m(a,se,this.Y).m(a,qc,this.Y).m(a,yc,this.Y)};Qj[B].Y=function(a){for(var b=null,c=a.v;null!=c&&!(b=uk[c.id])&&c!=this.c();)c=c[Na];if(b)switch(a[z]){case se:ej(b,a);break;case qc:a.J();a.v[La](Pf)||this.Sa(b);break;case yc:a.v[La](Pf)||this.Ta(b)}};I=Rj[B];I.Za=function(a){var b;if((b=a instanceof X?a:this.b.l)&&b!=this.b){a=b[na]();if(0==a[A])b=b.K,this.Z({inputtool:b},this.a);else for(var c=0;c<a[A];c++)b=a[c].K,this.Z({inputtool:b},this.a);Yj(this);$($e,Cc)}};I.$a=function(a){this.a.X(a instanceof X?a:this.a.l);Yj(this);$(ie,Cc);$(Vf,Cc);$(Gc,Cc)};I.Wa=function(a,b){var c=a[na]();if(0==c[A])(c=Xj(this,a.K),c)?b||(Ui(this.a,c),this.Xa()):$($e,Lc);else for(var d=c[A]-1;0<=d;d--)this.Wa(c[d],!0)};I.Xa=function(){$(ie,Lc);$(Vf,Lc);$(Gc,Lc)};
I.Z=function(a,b){if(a[Ga])for(var c=a[Ga],d=a.inputtools,e=0;e<d[A];e++)this.Z({inputtool:d[e],langName:c},b);else if(d=a.inputtool,c=a.langName,!Xj(this,d)){var e=b[r]().createNode(D),g=c,k=Ah(),c=k.ga(Mb,{"class":Nd,style:xf}),q=k.ga(Ob,Ld),w=k.ga(Ob,Od+Cj(d));k.Fb(c,q,w);k=Vj[Ba](d)?gf:ne;g&&(g=Hh(Ob,Pd,g+Ra),c[ma](g));g=Hh(Ob,{"class":Pd,dir:k},bk[d]);c[ma](g);Rh(da[Ia])&&wh(c,Qd);c=c.innerHTML;e.V=c;(g=bj(e))&&la(g,c);(c=e[r]())&&hj(c,e);e.K=d;b.add(e)}};
I.Ya=function(a){var b=this.a.l,c;if(b){if(0<a)(c=b.o)&&(c=c.o);else if(0>a&&(c=b.D,!c))return;this.a.add(b,c);Y(b);Yj(this)}};new Rj; })()
